### ISSUE TITLE
12月更新了ha这个集成实体都没了

### ISSUE THREAD

**Issue by HeartMaster** [NiaoBlush/impc_energy#3]
有没有用这个集成突然实体就剩更新提醒的，该怎么处理呢，还是就我有这个问题

**Comment by NiaoBlush** [comment]
我没遇到过这个问题, 不确定是否与新版ha有关
等我手头事情忙完我看一下

**Comment by HeartMaster** [comment]
看日志是一上来这个爬虫就访问失败了，很奇怪，另一个留言看起来它那个最近还能用
2025-01-11 16:56:12.366 ERROR (MainThread) [custom_components.impc_energy.energy_api] 获取基本信息错误, res: [{"code":2,"msg":"网络繁忙,请稍后重试！","data":[]}]
2025-01-11 16:56:12.368 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up impc_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/impc_energy/sensor.py", line 69, in async_setup_platform
    sensors = await get_sensors(energy_api, config)
  File "/config/custom_components/impc_energy/sensor.py", line 48, in get_sensors
    account_name = basic_info[ATTR_NAME]
![image](https://github.com/user-attachments/assets/d9448c9a-fdd0-48f0-a0f2-d7f71471b6cc)

**Comment by NiaoBlush** [comment]
@HeartMaster 我在不同日期不同时间测试这个接口，都提示网络繁忙。可能就是不再可用了，但是不排除是参数问题。
我之后重新抓取下看看情况。

**Comment by Sooocen** [comment]
获取电费的接口 增加了个参数 手动在energy.py

**Comment by Sooocen** [comment]
获取电费电量的接口 新增了一个参数 在header里新增qdly WECHAT即可 详情下图   ![Image](https://github.com/user-attachments/assets/84210e52-9d4c-4939-9897-dca522c54fd5)

@NiaoBlush 
@HeartMaster 手动修改下energy.py 文件中的 EnergyAPI.header也可以 如下图

![Image](https://github.com/user-attachments/assets/a05a2d32-6ca6-4355-b293-3cd4b0ae7c1a)

**Comment by HeartMaster** [comment]
添加了header后，数据又有了，但是我测试了两个账号，发现余额和公众号上的都不一样，看起来接口获取的余额像上个月的

**Comment by Sooocen** [comment]
应该是换接口了

**Comment by Sooocen** [comment]
应该是换接口了  换下接口名试试  

![Image](https://github.com/user-attachments/assets/216edc5d-e319-41ba-bd09-7774fb8e74d3)

**Comment by NiaoBlush** [comment]
@HeartMaster @Sooocen 
抓了一下, 公众号上显示的余额是通过`queryDfInfoNew`接口请求的, 余额字段是`syje` (可能是指'剩余金额')
原接口`dldfList`的余额字段是`zmye` (可能是指'账面余额?'), 也发起了请求, 但是不知道这个请求的响应用在了哪里
zmye要比syje多一点
我现在看不到电表, 不确定电表上的余额和这两个数字有什么关系, 不过为了和公众号保持一致, 暂定会切换到`queryDfInfoNew`接口

**Comment by HeartMaster** [comment]
缴费系统前段时间升级了个营销2.0，两个接口应该是新旧系统并轨运行

**Comment by NiaoBlush** [comment]
已在[v0.2.1](https://github.com/NiaoBlush/impc_energy/releases/tag/v0.2.1)中更新接口

最近在做v1.0更新，建议1.0发布后直接更新1.0

**Comment by NiaoBlush** [comment]
已发布[v1.0.0](https://github.com/NiaoBlush/impc_energy/releases/tag/v1.0.0)
